#!/usr/bin/python3
"""
Module to generate Pascal's triangle.
"""

def pascal_triangle(n):
    """
    Generate Pascal's triangle of size n.

    Args:
        n (int): The number of rows of the triangle.

    Returns:
        list: A list of lists containing the values of Pascal's triangle.
    """
    if n <= 0:
        return []

    triangle = []
    
    for i in range(n):
        row = [1] * (i + 1)  # Start each row with 1s
        
        # Calculate the values for the current row
        for j in range(1, i):
            row[j] = triangle[i - 1][j - 1] + triangle[i - 1][j]
        
        triangle.append(row)
    
    return triangle
